stages:
- name: deploy
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: |-
        #!/bin/bash
        kubeless function deploy func --runtime python2.7 --from-file func.py --handler func.handler
timeout: 60
notification: {}
