stages:
- name: build
  steps:
  - runScriptConfig:
      image: alpine:latest
      shellScript: |-
        zip deploy.zip func.py
        md5=($(sha256sum deploy.zip))
        envsubst < function2.yaml > deployment.yaml
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
