stages:
- name: build
  steps:
  - runScriptConfig:
      image: alpine:latest
      shellScript: |-
        apk update && apk add zip && apk add gettext
        FUNCZIP=deploy.zip
        zip $FUNCZIP func.py
        FUNCHASH=($(sha256sum $FUNCZIP))
        envsubst < function.yaml > deployment.yaml
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
