stages:
- name: build
  steps:
  - runScriptConfig:
      image: alpine:latest
      shellScript: |-
        apk update && apk add zip && apk add gettext && apk add coreutils
        export FUNCZIP=deploy.zip
        zip deploy.zip func.py
        export FUNCHASH=`sha256sum ./deploy.zip | awk '{print $1}'`
        envsubst < function.yaml > deployment.yaml
        cat deployment.yaml
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
