stages:
- name: build
  steps:
  - runScriptConfig:
      image: alpine/helm:latest
      shellScript: |-
        helm template ./functest > deployment.yaml
        cat deployment.yaml
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
