stages:
- name: build
  steps:
  - runScriptConfig:
      image: alpine:latest
      shellScript: |-
        echo "Hello world"
        ls -l
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
