apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
  labels:
    created-by: kubeless
    function: get-python
  name: get-python
  namespace: default
spec:
  deps: ""
  checksum: sha256:${FUNCHASH}
  function: ${FUNCZIP}
  function-content-type: url+zip
  handler: helloget.foo
  runtime: python2.7
  service:
    ports:
    - name: http-function-port
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      created-by: kubeless
      function: get-python
    type: ClusterIP
  timeout: "180"