apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
  labels:
    created-by: kubeless
    function: newtest
  name: newtest
  namespace: default
spec:
  deps: ""
  checksum: sha256:{{ .Files.Get "func.py" | sha256sum }}
  function: |
{{ .Files.Get "func.py" | indent 4 }}
  function-content-type: text
  handler: newtest.hello
  runtime: python2.7
  service:
    ports:
    - name: http-function-port
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      created-by: kubeless
      function: newtest
    type: ClusterIP
  timeout: "180"